# Generated by Django 3.0 on 2019-12-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelty',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='uploads/'),
        ),
    ]
