# Generated by Django 3.0 on 2020-01-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelty', '0002_auto_20191223_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelty',
            name='image',
        ),
        migrations.AddField(
            model_name='novelty',
            name='video',
            field=models.FileField(null=True, upload_to='', verbose_name='uploads/'),
        ),
    ]
